name: Code Quality Gate

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-quality:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      fmt_status: ${{ steps.fmt.outcome }}
      tflint_status: ${{ steps.tflint.outcome }}
      tfsec_status: ${{ steps.tfsec.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        id: fmt
        run: |
          terraform fmt -check -recursive > fmt-output.txt

      - name: Setup caching for TFLint
        uses: actions/cache@v4
        if: always()
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('./.github/tflint/.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        if: always()
        with:
          tflint_version: v0.51.0

      - name: Initialize TFLint
        if: always()
        run: tflint --init --config ./.github/tflint/.tflint.hcl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TFLint
        if: always()
        id: tflint
        run: |
          tflint --recursive --config $(realpath ./.github/tflint/.tflint.hcl) -f compact > tflint-output.txt

      - name: Run TFSec
        if: always()
        id: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          github_token: ${{ github.token }}
          format: default
          additional_args: --config-file ./.github/tfsec/tfsec.yml --out tfsec-output.txt --no-color

      - name: Upload results as artifacts
        uses: actions/upload-artifact@v4
        if: always() && (success() || failure())
        with:
          name: code-quality-results
          path: |
            ${{ github.workspace }}/fmt-output.txt
            ${{ github.workspace }}/tflint-output.txt
            ${{ github.workspace }}/tfsec-output.txt
        continue-on-error: true

  post-comment:
    needs: code-quality
    uses: ./.github/workflows/post_comment.yml
    with:
      fmt_status: ${{ needs.code-quality.outputs.fmt_status }}
      tflint_status: ${{ needs.code-quality.outputs.tflint_status }}
      tfsec_status: ${{ needs.code-quality.outputs.tfsec_status }}
      pr_number: ${{ github.event.pull_request.number }}