name: Terraform Code Quality Gate

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-quality:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      fmt_status: ${{ steps.fmt.outcome }}
      tflint_status: ${{ steps.tflint.outcome }}
      tfsec_status: ${{ steps.tfsec.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        id: fmt
        run: terraform fmt -check -recursive

      - name: Setup caching for TFLint
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('./.github/tflint/.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.51.0

      - name: Initialize TFLint
        run: tflint --init --config ./.github/tflint/.tflint.hcl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TFLint
        id: tflint
        run: tflint --config ./.github/tflint/.tflint.hcl -f compact

      - name: Run TFSec
        id: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          github_token: ${{ github.token }}
          tfsec_args: --config-file ./.github/tfsec/tfsec.yml

  post-comment:
    runs-on: ubuntu-latest
    needs: code-quality
    if: always()

    steps:
      - name: Post comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fmt_status = '${{ needs.code-quality.outputs.fmt_status }}'
            const tflint_status = '${{ needs.code-quality.outputs.tflint_status }}'
            const tfsec_status = '${{ needs.code-quality.outputs.tfsec_status }}'

            let comment = 'Code Quality Gate Results:\n\n'
            comment += `- Terraform fmt: ${fmt_status}\n`
            comment += `- TFLint: ${tflint_status}\n`
            comment += `- TFSec: ${tfsec_status}\n`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
              })